-- ============================================================
-- ZeroGate Platform — Database Schema
-- PostgreSQL / Supabase Migration
-- ============================================================

-- ─── CORE: Employees table (referenced by all portal tables) ─────────────────

CREATE TABLE IF NOT EXISTS public.employees (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    record_id VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    company VARCHAR(255),
    department VARCHAR(255),
    job_title VARCHAR(255),
    site_id UUID,
    email VARCHAR(255),
    phone VARCHAR(20),
    photo_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_employees_record_id ON public.employees(record_id);

ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;

CREATE POLICY "employees_select_policy" ON public.employees
    FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "employees_insert_policy" ON public.employees
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "employees_update_policy" ON public.employees
    FOR UPDATE USING (auth.role() = 'authenticated');

-- ============================================================
-- Table: clinic_examinations
-- Generated by ZeroGate Form Builder
-- ============================================================

CREATE TABLE IF NOT EXISTS public.clinic_examinations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    employee_id UUID REFERENCES public.employees(id) ON DELETE CASCADE,
    process_id UUID,  -- links to mobilization/recruitment process
    blood_pressure VARCHAR(255) NOT NULL,
    heart_rate NUMERIC NOT NULL,
    vision_test VARCHAR(100) NOT NULL CHECK (vision_test IN ('Pass', 'Fail')),
    drug_screen VARCHAR(100) NOT NULL CHECK (drug_screen IN ('Negative', 'Positive')),
    hearing VARCHAR(100) CHECK (hearing IN ('Normal', 'Impaired')),
    musculoskeletal VARCHAR(100) CHECK (musculoskeletal IN ('Normal', 'Impaired')),
    bmi VARCHAR(255),
    fit_for_work BOOLEAN DEFAULT false NOT NULL,
    restrictions VARCHAR(255),
    examiner_name VARCHAR(255) NOT NULL,
    examination_type VARCHAR(100) NOT NULL CHECK (examination_type IN ('Pre-Employment', 'Periodic', 'Return-to-Work')),
    valid_months NUMERIC NOT NULL,
    clinical_notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_clinic_examinations_employee_id ON public.clinic_examinations(employee_id);
CREATE INDEX IF NOT EXISTS idx_clinic_examinations_process_id ON public.clinic_examinations(process_id);

CREATE OR REPLACE FUNCTION update_clinic_examinations_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_clinic_examinations_updated_at
    BEFORE UPDATE ON public.clinic_examinations
    FOR EACH ROW
    EXECUTE FUNCTION update_clinic_examinations_updated_at();

ALTER TABLE public.clinic_examinations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "clinic_examinations_select_policy" ON public.clinic_examinations
    FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "clinic_examinations_insert_policy" ON public.clinic_examinations
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "clinic_examinations_update_policy" ON public.clinic_examinations
    FOR UPDATE USING (auth.role() = 'authenticated');


-- ============================================================
-- Table: security_clearances
-- Generated by ZeroGate Form Builder
-- ============================================================

CREATE TABLE IF NOT EXISTS public.security_clearances (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    employee_id UUID REFERENCES public.employees(id) ON DELETE CASCADE,
    process_id UUID,  -- links to mobilization/recruitment process
    badge_number VARCHAR(255) NOT NULL,
    badge_type VARCHAR(100) NOT NULL CHECK (badge_type IN ('Temporary', 'Permanent', 'Visitor', 'Contractor')),
    access_level VARCHAR(100) NOT NULL CHECK (access_level IN ('General', 'Restricted', 'High-Security', 'Administrative')),
    permitted_zones VARCHAR(255),
    background_check VARCHAR(100) NOT NULL CHECK (background_check IN ('Cleared', 'Pending', 'Flagged')),
    photo_captured BOOLEAN DEFAULT false NOT NULL,
    id_document_verified BOOLEAN DEFAULT false NOT NULL,
    issued_by VARCHAR(255) NOT NULL,
    valid_from DATE NOT NULL,
    valid_until DATE NOT NULL,
    security_notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_security_clearances_employee_id ON public.security_clearances(employee_id);
CREATE INDEX IF NOT EXISTS idx_security_clearances_process_id ON public.security_clearances(process_id);

CREATE OR REPLACE FUNCTION update_security_clearances_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_security_clearances_updated_at
    BEFORE UPDATE ON public.security_clearances
    FOR EACH ROW
    EXECUTE FUNCTION update_security_clearances_updated_at();

ALTER TABLE public.security_clearances ENABLE ROW LEVEL SECURITY;

CREATE POLICY "security_clearances_select_policy" ON public.security_clearances
    FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "security_clearances_insert_policy" ON public.security_clearances
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "security_clearances_update_policy" ON public.security_clearances
    FOR UPDATE USING (auth.role() = 'authenticated');


-- ============================================================
-- Table: hr_documents
-- Generated by ZeroGate Form Builder
-- ============================================================

CREATE TABLE IF NOT EXISTS public.hr_documents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    employee_id UUID REFERENCES public.employees(id) ON DELETE CASCADE,
    process_id UUID,  -- links to mobilization/recruitment process
    national_id VARCHAR(255) NOT NULL,
    passport_number VARCHAR(255),
    work_permit VARCHAR(255),
    contract_type VARCHAR(100) NOT NULL CHECK (contract_type IN ('Permanent', 'Fixed-Term', 'Contractor', 'Intern')),
    start_date DATE NOT NULL,
    end_date DATE,
    emergency_contact_name VARCHAR(255) NOT NULL,
    emergency_contact_phone VARCHAR(20) NOT NULL,
    bank_account VARCHAR(255),
    tax_id VARCHAR(255) NOT NULL,
    marital_status VARCHAR(100) CHECK (marital_status IN ('Single', 'Married', 'Divorced', 'Widowed')),
    email_address VARCHAR(255) NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    address TEXT,
    hr_notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_hr_documents_employee_id ON public.hr_documents(employee_id);
CREATE INDEX IF NOT EXISTS idx_hr_documents_process_id ON public.hr_documents(process_id);

CREATE OR REPLACE FUNCTION update_hr_documents_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_hr_documents_updated_at
    BEFORE UPDATE ON public.hr_documents
    FOR EACH ROW
    EXECUTE FUNCTION update_hr_documents_updated_at();

ALTER TABLE public.hr_documents ENABLE ROW LEVEL SECURITY;

CREATE POLICY "hr_documents_select_policy" ON public.hr_documents
    FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "hr_documents_insert_policy" ON public.hr_documents
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "hr_documents_update_policy" ON public.hr_documents
    FOR UPDATE USING (auth.role() = 'authenticated');
